media: 
  input: static/images
  output: /images
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/blog'
    filename: '{primary}.md'
    view:
      fields: [ title, date ]
    fields:
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-MM-dd
      - name: title
        label: Title
        type: string
      - name: image
        label: 'Hero Image'
        type: image
      - name: image_alt
        label: 'Hero Image Alt Text'
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: layout
        hidden: true
        default: post