media: 
  input: static/images
  output: /images
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/blog'
    view:
      fields: [ title, date ]
    fields:
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-MM-dd
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text